### ISSUE TITLE
Error: `stream did not contain valid UTF-8`

### ISSUE THREAD

**Issue by jeertmans** [xgillard/anycat#1] opened 2022-04-13 13:48 UTC
Hello, is it on purpose that your program panicks as soon as it encounters some non-valid UTF-8 character in an archive ?

Wouldn't it be better if it skipped silently things that can't be read? Or read it using [`String::from_utf8_lossy`](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_lossy) for example?

**Comment by xgillard** [comment] 2022-04-13 16:02
Hi Jerome, 

I don't know if you've looked at the code of `lib.rs` but you'll see that it's kind of trivial. None of the decompression is actually made in this crate. So the error you're getting is likely caused by one of the underlying readers/writers. If so, it might either be a true bug in that lib (which might be fixed by upgrading deps) or it might just as well be an expected behavior. 

If I were to be the one writing the decompression algorithm I would probably expect to either panic (or at least return an error) when encountering invalid characters. My take in that case would be that if the file contains invalid characters, it's probably because the file is corrupt. In which case it should probably not be output. I'm no big fan of skipping some content bc it does not let you retrieve your original content (which is kind of the point). 

But that's just me, and I totally understand that you might have another opinion about this. If you want to try to adapt the lib for your use case and need some help, I'll do my best to help you out.

**Comment by jeertmans** [comment] 2022-04-18 10:42
Hello Xavier,

Following the discussion we had in private, I think we can close this issue :-)
My first goal was just to ring a bell to see if this behavior was intended or not.

**Closed as completed** 2022-04-18 10:42 UTC
